name: Azure Web App CI/CD

on:
  push:
    branches:
      - main
      - enhancement-chat-widget # Add this if you're working on feature branches
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - enhancement-chat-widget # Add this if you're working on feature branches

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version your app requires

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: |
          npm run build  # Customize this command if necessary for your build process

      - name: Azure Web Apps Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-app-name  # Replace with your Azure Web App name
          slot-name: 'production'  # You can use other slots, if necessary
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}  # Publish Profile secret in GitHub
          package: ./path-to-your-build-folder # Specify the correct path to your build output folder, like `build` or `dist`

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-app-name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          action: "close"
